In [1]:
from sklearn.naive_bayes import MultinomialNB
import numpy as np
import pandas as pd

In [3]:
X = np.random.randint(5,size=(6,100))
y = np.array([1,2,3,4,5,6])

In [4]:
print(X)
print()
print(y)

[[0 2 4 3 3 3 4 3 3 2 4 4 0 0 2 0 1 2 0 2 1 1 1 1 0 4 0 2 1 1 3 1 4 1 2 4
  3 4 1 2 2 0 1 2 2 0 4 2 1 3 0 0 2 3 3 2 3 2 3 1 0 3 2 4 2 3 4 1 2 4 2 3
  1 1 4 2 0 4 1 0 1 4 4 4 4 0 0 2 3 0 3 2 1 4 1 2 1 3 1 1]
 [1 3 2 3 1 3 1 2 0 4 1 0 1 1 0 0 4 3 1 1 2 1 2 3 1 0 1 3 3 2 4 4 4 4 1 1
  1 3 4 2 1 4 0 0 0 1 4 4 2 0 0 2 2 2 3 3 3 4 3 4 3 3 2 4 4 2 2 3 3 2 3 1
  3 0 4 1 2 3 2 4 0 4 4 3 0 1 3 0 4 4 3 3 4 0 3 0 1 0 0 3]
 [3 1 3 0 2 3 3 1 1 3 3 4 4 1 3 0 3 3 4 4 4 0 2 2 3 0 0 4 0 2 1 4 3 4 3 2
  3 0 2 2 3 3 4 3 2 3 2 4 4 2 3 2 2 3 1 3 2 0 4 2 1 3 1 4 4 1 4 0 2 2 0 0
  2 4 2 4 0 2 4 2 0 2 1 0 1 3 1 0 4 3 2 4 0 3 4 4 1 2 0 2]
 [4 4 0 3 4 3 2 0 0 1 3 2 0 3 4 0 3 1 0 1 1 2 1 2 3 4 0 3 3 1 3 3 2 4 1 3
  4 1 1 1 1 2 1 1 3 0 0 3 0 4 3 4 3 2 3 1 3 3 3 1 4 3 3 0 1 3 1 3 3 0 1 4
  0 2 4 3 0 1 2 0 2 3 0 1 3 1 2 2 4 0 4 4 4 4 1 4 1 1 2 2]
 [0 0 3 4 4 3 2 1 2 0 2 1 2 1 2 4 3 4 3 3 3 0 3 0 4 4 2 2 1 4 2 2 1 1 1 4
  3 4 0 0 2 3 3 3 4 3 2 2 4 1 4 0 4 0 3 3 3 1 1 4 1 0 4 4 4 1 1 4 1 1 3 1
  3 2 2 1 4 2 2 2 3 3 2 

In [5]:
# 문제
clf = MultinomialNB()

In [6]:
clf.fit(X,y)

MultinomialNB()

In [16]:
# 문제
# 4번째 데이터 class 예측해보세요 (reshape)
clf.predict(X[3].reshape(1,-1))
clf.predict_proba(X[3].reshape(1,-1))

array([[1.03672504e-26, 1.01139262e-34, 2.73263674e-33, 1.00000000e+00,
        9.83649138e-38, 6.57146128e-34]])

In [14]:
X[3,:].reshape(1,-1)

array([[4, 4, 0, 3, 4, 3, 2, 0, 0, 1, 3, 2, 0, 3, 4, 0, 3, 1, 0, 1, 1, 2,
        1, 2, 3, 4, 0, 3, 3, 1, 3, 3, 2, 4, 1, 3, 4, 1, 1, 1, 1, 2, 1, 1,
        3, 0, 0, 3, 0, 4, 3, 4, 3, 2, 3, 1, 3, 3, 3, 1, 4, 3, 3, 0, 1, 3,
        1, 3, 3, 0, 1, 4, 0, 2, 4, 3, 0, 1, 2, 0, 2, 3, 0, 1, 3, 1, 2, 2,
        4, 0, 4, 4, 4, 4, 1, 4, 1, 1, 2, 2]])

In [17]:
# 전체 훈련 데이터 예측
clf.predict(X)

array([1, 2, 3, 4, 5, 6])