1. 역함수와 역변환
 - 역행렬

In [3]:
import numpy as np

A = np.matrix([[1,0,0,0],[2,1,0,0],[3,0,1,0],[4,0,0,1]])

print(A,'\n')
print(np.linalg.inv(A))

[[1 0 0 0]
 [2 1 0 0]
 [3 0 1 0]
 [4 0 0 1]] 

[[ 1.  0.  0.  0.]
 [-2.  1.  0.  0.]
 [-3.  0.  1.  0.]
 [-4. -0. -0.  1.]]


In [6]:
# 전치행렬(Transpose)

a = np.arange(15).reshape(3,5)
print(a)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [7]:
np.transpose(a)

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [8]:
# 고유값, 고유벡터

a = np.array([[5,-1],[-2,1]])
np.linalg.eig(a)

(array([5.44948974, 0.55051026]),
 array([[ 0.91209559,  0.21927526],
        [-0.40997761,  0.97566304]]))

In [9]:
# w : 고유값, v : 고유벡터
w,v = np.linalg.eig(a)
print(w) # 고유값
print()
print(v) # 고유벡터(단위벡터로 정규화함)

[5.44948974 0.55051026]

[[ 0.91209559  0.21927526]
 [-0.40997761  0.97566304]]


In [10]:
b = np.array([[1,3],[4,2]])

np.linalg.eig(b)

(array([-2.,  5.]),
 array([[-0.70710678, -0.6       ],
        [ 0.70710678, -0.8       ]]))

In [11]:
w,v = np.linalg.eig(b)

print(w,'\n')
print(v)

[-2.  5.] 

[[-0.70710678 -0.6       ]
 [ 0.70710678 -0.8       ]]
