In [29]:
v1 = 'abcde'
vtel = '031)345-0834'
# 문자열 분리
#v1.split(sep) #분리 구분기호
'a/b/c/d'.split('/')[0:3]
# 위치값 리턴
# 'abcd'.find(sub, #위치값을 찾을 대상
#            start, #찾을 위치(시작점)
#            end    #찾을 위치(끝점))

v1
v1.find('b')

# ex. 전화번호에서 지역번호 추출할려고 함
# ')'위치를 확인해서 그 이전까지 추출하시오

vtel[:(vtel.find(")"))]

# 포함 횟수
'abcabcabc'.count('a')

# 형(type) 확인
type(v1) # 데이터 타입
v1.isalpha() #문자확인
v1.isnumeric() #숫자 확인

#대소문자 확인
v1.isupper() #대문자확인
v1.islower() #소문자 확인

# 문자열 결합
'a' + 'b' + 'c'

# 문자열 길이
len(v1)
3/len(v1)

# 연습문제
vname='Jeong'
vemail='Jeong@gmail.com'
jumin = '901010-111111'

#1. 이름의 두번째 글짜가 m인지 확인
vname[1] == 'm'
vname[1] == 'r'

#2. vemail에서 이메일 아이디만 추출
vemail[:vemail.find('@')]

# 3. 주민번호에서 여자인지 확인
jumin[7]== 2



False

In [79]:
# 조건문 반복문

#논리연산자
# and
# or
# not
v1 = 1
(v1>=3) and (v1<=7) #3 7 사이
(v1>=3) & (v1<=7) #3 7 사이

(v1<=3) or (v1>=7) #3보다 작고  7보다 큼
(v1<=3) |(v1>=7) #3보다 작고  7보다 큼

not(v1 == 1)

# 조건문 fi

# 형식
# if 조건1:
#     조건1이 참(True)일때 실행
# elif 조건2:
#     조건1이 거짓이고 조건2가 참(True)일때 실행
#.....
# else:
#     위의 조건들이 거짓(False)일때 실행

v1 = 4
if v1>5:
    print('A')
else:
    print('B')

#리스트는 불가
# l1 = [1,3,5,7,9]
# if l1>5:
#     print('A')
# else:
#     print('B')

# 반복문
# 객체의 각 원소에 동일한 연산처리 진행할 경우 사용
# 1.for 문: 정해진 횟수, 대상이 있을경우

#for 반복변수 in 반복할 대상(범위):
#    반복 실행할 문장

# 1~10 까지 출력하시오
for i in range(1,11):
    print(i)
j = 0
#예제
#다음의 리스트를 선언하고 5보다 클경우, 'A', 작거나 같을경우 'B'
l1 = [1,3,5,15,25]
for i in l1:
    if i > 5:
        print('A')
    else:
        print('B')

# 위 리스트에서 각 원소에 10을 더해서 출력
# j = 0
# for i in l1:
#     l1[j] = i+10
#     j = j + 1
l2 = []
for i in l1:
    l2.append(i+10)
print(l2)
#while문: 조건에 따른 반복을 실행하는 경우

# while 조건:
#     조건이 참일 때 반복 문장

i = 1
while i <= 10:
    print(i)
    i = i + 1

# 문제
# 1~100까지 합

vsum = 0
for i in range(1,101):
    vsum = i + vsum

print(vsum)

# i      vsum      일반화
# 1       1         vsum + 1
# 2       1+2       vsum + 2
# 2       1+2+3     vsum + 3
# 2       1+2+3+4   vsum + 4
vvvv=sum(i for i in range(1,101))
print(vvvv)

# 1~100까지 짝수 총합
j = 0
for i in range(1,101):
    if i%2 == 0:
        j += i
print(j)
# 반복제어문 5에다 적용할 경우
# 1.continue : 특정 조건일 경우 반복문 스킵(1,2,3,4,6,7,8,9,10)
# 2.break    : 특정 조건일 경우 반복문 종료 (정지조건)
# 3.exit     : 특정 조건일 경우 프로그램을 종료
# 4.pass     : 문법적으로 오류가 발생시킺 않기 위해 자리를 채우는 역할(1,2,3,4,5,6,7,8,9,10)


# for i in range(1,11):
#     if i == 5:
#         pass
#     print(i)

# 예제
# 1~10 출력, 5제외

for i in range(1,11):
    if i == 5:
        continue
    print(i)
#1
#2
#3
#4
#5
#6
#7
#8
#9
#10

# 1~10 출력, 5일때 반복문 종료

for i in range(1,11):
    if i == 5:
        break
    print(i)
#1
#2
#3
#4

# 1~10 출력, 5일때 프로그램 종료

#for i in range(1,11):
#    if i == 5:
#        exit(0)
#    print(i)

v1 = 1
if v1 > 10:
    pass
else:
    print('b')
#IndentationError: expected an indented block

# 문제
# 1부터 100까지 누적합이 최초 2000 이 이상이 되는 시점의 k값과 총 하을 출력하세요.
# 1 + 2 + 3 + ... + k >= 2000
vsum = 0
for i in range(1,101):
    vsum += i
    if vsum >= 2000:
        print(i,j)
        break




B
1
2
3
4
5
6
7
8
9
10
B
B
B
A
A
[11, 13, 15, 25, 35]
1
2
3
4
5
6
7
8
9
10
5050
5050
2550
1
2
3
4
6
7
8
9
10
1
2
3
4
b
63 2550


In [103]:
#사용자 정의 함수
# 사용자가 정의하는 함수의 형태
# input과 output 관계를 내부에서 정의
# def, lambda(축약형)

# 함수 정의
# f(x) = x + 1

#1. def 방식

# def 함수이름(인수1,인수2,......):
#     함수 본문
#     return 반환할 객체

# 숫자를 넣어서 곱하기 10한 값을 반환

def f_mul(x):
    v1 = x * 10
    return v1

f_mul(10)

# 두 숫자(두개의 인자를 넣구나!) 넣어서 두 숫자의 곱 반환
def f_2_mul(x,y):
    return x * y
print(f_2_mul(2,10))

# 인수에 default 값 (기본값 선언)

# def f_d(x=1,y):
#     return x* y

# 첫번째 인수에 기본값을 정의하면, 뒤에 나오는  인수도 기본값 정의해야 한다.
#SyntaxError: non-default argument follows default argument

def f_d(x,y=1):
     return x* y
# default 값을 갖는 인수는 맨 뒤에 배치

print(f_d(1))

# lambda 축약형
# 비교적 단순한 연산 및 리턴시 사용

# 예제: 숫자를 넣을거예요. 여기에 10을 곱한값을 리턴하세요.
f1 = lambda x: x*10
f1(5)

# 문제
# 3개 숫자를 전달받아 첫 번째와 두 번째 합에 세번째 숫자의 곱 리턴

f2 = lambda x,y,z:(x+y)*z
f2(2,5,3)

#map 함수
f1 = lambda x:x*10
f1(4)

l1 = [1,2,5,10]
f1(l1)
#리스트가 10번 반복

#1) for문 처리
l2 = []
for i in l1:
    l2.append(i+10)
print(l2)

# 2) 사용자 정의 함수 + map

# map(func,        #적용할 함수
#    iterable)     #추가할 인수

f1(4)
map(f1,l1)
#<map at 0x14b397e1640>
list(map(f1,l1))

#연습해 볼까요?
# 하나의 숫자를 전달받을거에요. 10보다 크면 3을 곱하고, 작거나 같으면 2를 곱한 결과를 리턴
def f3(x):
    if x > 10:
        return x*3
    else:
        return x*2
    
l2 = [3,5,7,11]
list(map(f3,l2))

20
1
[11, 12, 15, 20]


[6, 10, 14, 33]

In [66]:
# 자료구조
# 리스트(기본구조)
# 2. 튜플(상수,불변)
# 3. 딕셔너리(key:alue) << 자바(json) {1:'ㅇㅅㅇ',2:'ㅡㅅㅡ',3:'>ㅅ<'}
# 4. 세트(set) : 집합
# 5. 배열(numpy)
# 6. 판다스 구조(Series,DataFrame)

# 넘파이
# 배열(array) 생성, 연산

#배열(array): 하나의 데이터 타입 허용(int, float), 다차원 자료구조
import numpy as np
np.array([1,2,3])
# array([1,2,3]) 1차원 배열

np.array([[1,2,3],[4,5,6],[7,8,9]])
#array([[1,2,3],
#      [4,5,6],
#      [7,8,9]])
# 2차원 배열 (수리적 모형: 행,열)

np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
#np.array([[[1,2,3],
#          [4,5,6]],
#          [[7,8,9],
#          [10,11,12]])
# 3차원 배열

np.arange(1,26)
#array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
#       18, 19, 20, 21, 22, 23, 24, 25])
np.arange(1,26).reshape(5,5)
# array([[ 1,  2,  3,  4,  5],
#        [ 6,  7,  8,  9, 10],
#        [11, 12, 13, 14, 15],
#        [16, 17, 18, 19, 20],
#        [21, 22, 23, 24, 25]])

a1 = np.arange(1,26)
type(a1)

# 색인
a2 = np.array([[1,2,3],[4,5,6],[7,8,9]])
# array([[1, 2, 3],
#        [4, 5, 6],
#        [7, 8, 9]])
#array[행 선택, 열 선택]
a2[1,:]
#array([4, 5, 6])

# 정수 색인(두번째 열 선택: 차원 축소 발생)
a2[:,1]
#array([2, 5, 8]) - reshape해서 리턴함

# 슬라이스 색인(두번 째 열 선택: 차원축소 발생 안함)
a2[:,1:2]
# array([[2],
#        [5],
#        [8]]) - 원본 그대로 가져옴

# a2에서 1,3행 선택
a2[0:3:2,:]
a2[[0,2],:]

# a2에서 1,3 열 선택
a2[:,0:3:2]
a2[:,[0,2]]

a2
# array([[1, 2, 3],
#        [4, 5, 6],
#        [7, 8, 9]])
a2[1,1] # 5 return
a2[[1,2],[1,2]] # [5,9] return
# >>> a2[1,1],a2[2,2] 포인트 인덱싱
# 2개의 포인트(점) 출력
#색인함수 (ix()) 사용하여 해결

#a2[[1,2],[1,2]] 여기서 1,2행이랑 1,2열 겹치는 부분을 추출하려고 했는데 그 값이 5,9로 나와서 원하는 값을 못 얻어서 a2[np.ix_([1,2],[1,2])] 이 방법으로 하셨다는 뜻이죠?


a2[np.ix_([1,2],[1,2])]
# array([[5, 6],
#        [8, 9]])

a = np.arange(10).reshape(2, 5)
a
#ixgrid = np.ix_([0, 1], [2, 4])
#ixgrid
#ixgrid[0].shape, ixgrid[1].shape
#a[ixgrid]
#ixgrid = np.ix_([True, True], [2, 4])
#a[ixgrid]
#ixgrid = np.ix_([True, True], [False, False, True, False, True])
#a[ixgrid]
#np.ix_? 도움말

# 조건 색인
a2 > 5
#array([[False, False, False],
#       [False, False,  True],
#       [ True,  True,  True]])

a2[a2>5]
#array([6, 7, 8, 9]) True만 출력

a2[:,0] > 5 # 첫번째 컬럼 가져와서 5 이상인 행만 선택
a2[a2[:,0] > 5]
# 조건의 결과를 행방향에 색인 값으로 전달

array([[7, 8, 9]])

In [43]:
'abc'


array([[1, 3],
       [7, 9]])

array([[13, 14],
       [18, 19]])